### ISSUE TITLE
Consider building a CI/CD pipeline for this project

### ISSUE THREAD

**Issue by orpheustaken** [victorinknov/confiadesign#2]
It would make the deployment automatic by only pushing to a specific branch. We can use Github Actions for that.

**Comment by victorinknov** [comment]
Currently most of the project is static. Other than responsiveness, there's not much to test. But the project is integrated with AWS and all improvements are put into production minutes after the merge. Thanks for your suggestion!
![image](https://user-images.githubusercontent.com/56061950/190515766-7ec3f14c-3a9d-414d-82ea-a270d6e16766.png)

**Comment by orpheustaken** [comment]
Perfect!
